export const PORTFOLIOPROJECTS = [
    {
        // for title page
        id: 'portfolio1',
        title: 'Transcarry',
        description: 'Design by Empathy.',
        imageURL: 'url(images/P1.png)',
        videoURL: 'videos/P1.mp4',
        symbolURL: 'symbols/P1.svg',
        bigtext: 'Shopping that waits for you where you need it',
        // for project page
        imageCover: "../images/P1.png",
        textProjectDescription: "This project on the theme of Sustainability. We reflected on the issues of car pollution and reducing carbon emissions. With convenience standing out as the main driver behind the widespread use of car. Therefore, convenience often being the motivation for social non-working woman. Therefore, we aimed at creating a sustainable solution that encourages sustainable modes of transport.<br><br>Our idea was around storing groceries whilst in the city and having it automatically transported (like plane luggage) to the destination. Our, 47 year old Alice, might be going to a social event after, in charge of chores around the city - so we wanted it to be convenient for them. ",
        imageContentRight: "../images/P1.png",
        textProcessLeft: "In this Design For Empathy process, we first created personas with a user experience story and a problem statement. We plotted an experience map before exploring solutions on a verb diagram. ",
        imageProcessCards: [
            {image: "../images/P1Extras/personas.png", text:"Personas"},
            {image: "../images/P1Extras/ExperienceMap.png", text:"Experience Map"},
            {image: "../images/P1Extras/transcarryUserJourney.png", text:"User Journey"},
            {image: "../images/P1Extras/verbBoard.png", text:"Verb Board"},
        ],
        imageCenter: "../images/P1A.png",
        textImproving: "To improve our solution, we could explore alternative carrier methods like crates and compare them to traditional delivery trucks. The main advantage of using TransCarry is preserving the in-store shopping experience, which we can incentivize through discounts, cooking workshops, and partnerships with local shops. Additionally, we can enable customers to scan items in-store, automatically sending them to destination lockers for added convenience and a more seamless shopping experience.",
        textMyExperienceAndOpinion: "Creating personas is a traditional but important stage. Coming up with a persona helps to find insightful problems. I like ther focus on a verb and its touchpoints to help find solutions. However, I feel a disconnect between this verb/touchpoint stage and the persona stage, as the emotional needs of the persona does not take priority, instead their actions.",
        imageResultsCards: [
            {image:"../images/P1Extras/SolutionStatement.png", text:"Final Solution Statement"},
            {image:"../images/P1Extras/oldOutput.png", text:"Another generation"},
            {image:"../images/P1Extras/UserJourneySketch.jpeg", text:"Original User Journey Sketch"},
        ],
    },

    {
        id: 'portfolio2',
        title: 'Dog-beds',
        description: 'Design for Environmental and Social Transformations',
        imageURL: 'url(images/P2.png)',
        videoURL: 'videos/P2Square.mp4',
        symbolURL: 'symbols/P2.svg',
        bigtext: 'Upcycling old fabrics to Dog-beds',
        imageCover: "../images/P2.png",
        textProjectDescription: "The life cycle of a product, and the complete experience of touchpoints was empahsized. The focus was on bringing new life to an old product. <br> <br> In our solution, we decided upon upcycling dog beds. For the experience, When customers enter a store, they can select a bed size, and can either donate fabric or pay a supplementary fee to cover the balance. This fee also funds fabric waste purchases from companies, preventing waste. All donated fabrics are categorized, quality- checked, and sanitized. With donors able trace their contributed clothing, watching its transformation into a bed throughout the week. Upon bed completion, customers are notified for pickup and can snap a memorable photo with their dog and the new bed at the in-store booth. ",
        imageContentRight: "../images/P2Extras/DonationStore.png",
        textProcessLeft: "We focused on the most important attributes to our topic to use as keywords in our generatoin. Using weightings (according to our refinement matric), we highlighted the keywords to change the focus and direction of AI Generation. Interestingly, MidJourney inspired me to make dog beds out of old fabrics after generating our initial idea of blankets placed a dog within blankets instead of a person when manipulating weightings of certain words within the prompt. <br> There are several active touch points: the collection of old fabrics, processing and the new product.<br> We wanted to encourage donation, and thought about the personalisation of using one’s own fabrics. Specifically, the scent of a dog’s owner fabric can be comforting to the dog. This became the unique selling point of our proposition.",
        imageProcessCards: [
            {image:"../images/P2Extras/1GenerativeMatric.png", text:"Generative Matrix with our first item of Amenities Kits"},
            {image:"../images/P2Extras/Refinement Matric.png", text:"Refining Prompts"},
            {image:"../images/P2Extras/Interaction Diagram.png", text:"Interaction Diagram"},
            {image:"../images/P2Extras/MidjourneyScreenshot.png", text:"Midjourney Screenshot - turning people into dogs"},
        ],
        imageCenter: "../images/P2Extras/PhotoboothDog.png",
        textImproving: "In order to improve our solution, we could partner with charity shops for clothes that haven’t sold, allowing users to easily access high-quality fabrics for their dog beds and may develop for other pets.",
        textMyExperienceAndOpinion: "This was particularly exciting using architectural processes in experience design. This tweaking of certain attributes makes you really consider what is important for your user. It provides a way to explore. For us, we used the morphological box process to open the scope, as we found our new problem and solution through Midjourney.",
        imageResultsCards: [
            {image:"../images/P2Extras/PhotoboothDog.png", text:"Photobooth Dog"},
            {image:"../images/P2Extras/celerei_photo_booth._A_girl_fa8be3d2-c3a2-4fb9-b920-cb85e1ea4c8e.png", text:"Example of Generation attempts"},
            {image:"../images/P2Extras/celerei_photo_shoot_setup_with_light_orange_background._A_girl__50670507-4fdb-4fba-8b0b-843098664748.png", text:"Turning into an experience"},
            {image:"../images/P2Extras/myPhotoshop.png", text:"My Photoshop image to try getting the right elements"},
            {image:"../images/P2Extras/weightingClothes.png", text:"Output looks Photoshopped too!"},
        ],
    },

    {
        id: 'portfolio3',
        title: 'Architech',
        description: 'Design Instruments for Architects',
        imageURL: 'url(images/P3.png)',
        videoURL: 'videos/P3.mp4',
        symbolURL: 'symbols/P3.svg',
        bigtext: 'Elevating Design with flawless plans from concepts - visible and automatically correct',
        imageCover: "../images/P3.png",
        textProjectDescription: "This project was to focus on the needs of Architects. Our initial user group pain was the manual task of transferring paper plans into digital. We took it further through this method of inspiration and our solution was an app that will translate the paper concept sketches into 3D digital models by making a quick rendering. The app would, provide feedback and auto-correct on your paper plans, including revising dimensions using design rules and provide advice along guidelines.",
        imageContentRight: "../images/P3.png",
        textProcessLeft: "Our process involved taking inspiration and applying it for an architectural problem. We used a quadrant to realise our solution. Taking a problem and solution from another domain and applying it to our architectural problrm. Our inspiration came from scanning physical cards to create a virtual card on your mobile.",
        imageProcessCards: [
            {image:"../images/P3Extras/image (6).png", text:"Inspiration Template"},
            {image:"../images/P3Extras/image (7).png", text:"Experience Journey"},
            {image:"../images/P3Extras/image (8).png", text:"Project Description"},
            {image:"../images/P3Extras/image (9).png", text:"Relevance and Impact"},
        ],
        imageCenter: "../images/P3Extras/Card.png",
        textImproving: "In terms of improvement, we could present the 3D model in Augment Reality form or an instant 3D print of the model is created. The app will translate the paper concept sketches into 3D digital models by making a quick rendering. The app would, provide feedback and auto-correct on your paper plans, including revising dimensions using design rules and provide advice along guidelines.Another idea was scanning multiple paper concept sketches, finding patterns in style from user data for the app to create predictive design recommendations.",
        textMyExperienceAndOpinion: "This was a relatively effective method for finding a solution. However, there were risks in that we had an architectural problem and idea, and we reversed the process to find a solution in another domain. I had recently come across a similar method in my Design Research for Innovation module - as a method named State of the Art, which took inspiration from other domains especially contemporary art.",
        imageResultsCards: [
            {image:"../images/P3Extras/image (4).png", text:"Problem 1"},
            {image:"../images/P3Extras/image (5).png", text:"Problem 2"},
    
            {image:"../images/P3Extras/rendering.png", text:"Generations - rendering to screen"},
        ],
    },

    {
        id: 'portfolio4',
        title: 'Dunlop Golf Glove',
        description: 'Design With Style',
        imageURL: 'url(images/P4.png)',
        videoURL: 'videos/P4.mp4',
        symbolURL: 'symbols/P4.svg',
        bigtext: 'A stylish recovery inspired',
        imageCover: "../images/P4.png",
        textProjectDescription: "We took a patent and explored several styles and forms it might take. Our patent was a wearable hand vibrating rehabilitation device that offers people with finger dysfunction a novel and adaptable treatment option. It activates neural pathways and promotes rehabilitation by using a multimodal approach that combines vibration, sound, light, and electric stimulation. Our solution led to a white Dunlop Golf Style glove. With its more classic aesthetic, it allows for familiarity without the cumbersome, intrusive nature of retro designs. Because older people generally have a lower level of proficiency with current technology, it was designed to be minimalistic in order to reduce frustration. Its sporty design could evoke a positive feeling through connotations of freedom of movement, while also maintaining a discreet appearance as a medical device.",
        imageContentRight: "../images/P4.png",
        textProcessLeft: "We first created a persona for someone who would use the patent and touchpoints of receiving the device. We utilised a grid of two style attributes we wanted to focus on and its opposing pairs. We explored generated solution styles based on the emphasis of these attributes.",
        imageProcessCards: [
            {image:"../images/P4Extras/P4_Persona.png", text:"Persona and Touchpoints "},
            {image:"../images/P4Extras/P4_Grid.png", text:"Grid used"},
        ],
        imageCenter: "../images/P4Extras/P4_7.png",
        textImproving: "An initial thought of improving our solution would be three clear plastic buttons with an off button, + button and - button that will lower or increase the stimulation and an emergency off button. This will give the user control, whilst keeping it simple for the older generation.",
        textMyExperienceAndOpinion: "Exploring subtle changes in style really pinpointed our user's needs. <br> Firstly though, this approach needed carefully selected adjectives for the axes, and it was intriguing because of its distinctive visual style. After much consideration, we chose a flexible patent that we could explore various forms. This raises the question: is styling just superficial if form follows function? Possibly not, as styling has the power to elevate functionality beyond merely aesthetics and convey cultural and emotional significance, like nostalgia in retro designs.",
        imageResultsCards: [
            {image:"../images/P4Extras/P4_1.png", text:"Second Agreement of Final Solution Style"},
            {image:"../images/P4Extras/P4_2.png", text:"Modern-Soft,"},
            {image:"../images/P4Extras/P4_3.png", text:"Modern-Hard"},
            {image:"../images/P4Extras/P4_4.png", text:"Retro-MediumSoft"},
            {image:"../images/P4Extras/P4_5.png", text:"Retro-Hard"},
            {image:"../images/P4Extras/P4_6.png", text:"MediumModern-Soft"},
        ],
    },

    {
        id: 'portfolio5',
        title: 'Winter in Chisnau',
        description: 'Design for Context',
        imageURL: 'url(images/P5A.png)',
        videoURL: 'videos/P5BSquare.mp4',
        symbolURL: 'symbols/P5.svg',
        bigtext: 'Improving the city, improving dog welfare',
        imageCover: "../images/P5B.png",
        textProjectDescription: "In this project week, we aimed to leverage the specific characteristics of a location, for addressing the problem of stray dogs.  ",
        imageContentRight: "../images/P5Extras/P6_city.png",
        textProcessLeft: "We found a city with a problem of stray dogs and created personas of dogs who might live there using WWWWH - Who (Persona), Where (Topology), When (Touchpoints), Why (Problems) and How (Ideas for Solutions). When creating solutions, we focused on the locations attributes and its contetual relevance, using these contextual keyworks within our prompts.",
        imageProcessCards: [
            {image:"../images/P5Extras/P6_grid.png", text:"template grid for Personas"},
            {image:"../images/P5Extras/P6_safeInspo.png", text:"Inspiration - Photo by Traffic Safety Corp. "},
            {image:"../images/P5Extras/P6_warmInspo.png", text:"Inspiration - Photo by UNECESO "},
            {image:"../images/P5Extras/P6_DogGuidesInspo.png", text:"Inspiration - Post-Soviet visual. Abandoned Soviet cafe in Chisinau, Moldova, 2015. By Soviet Visuals"},
        ],
        imageCenter: "https://images.unsplash.com/photo-1629045951387-6d86eb2aad3d?q=80&w=2370&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        textImproving: "...",
        textMyExperienceAndOpinion: " Finding a holistic contextual solution for non-human characters, such as dogs, was satisfying yet difficult at the same time.  It also prompted consideration of sustainable practices for repurposing places and buildings. I propose that before delving into solutions, we could introduce an intermediary 'Where' phase.. Furthermore, I think it's better to concentrate on honing one idea rather than distributing my efforts across several, as certain responses seemed forced.",
        imageResultsCards: [
            {image:"../images/P5Extras/P6_1.png", text:"Dog Guide - Dog Social Room"},
            {image:"../images/P5Extras/P6_2.png", text:"Shelter - Dog on Roof"},
            {image:"../images/P5Extras/P6_3.png", text:"Shelter - Glass Shelters"},
            {image:"../images/P5Extras/P6_4.png", text:"Dog Guide - generated"},
            {image:"../images/P5Extras/P6_5.png", text:"Dog Guide - Dog Social Room"},
            
        ],
        subProjects: [
            {id: 'projectA',
            verb:'To Stay Warm',
            projectTitle:'Flat Top Dog Shelters',
            description:'The solution involves transforming Chisinau’s flat rooftops into insulated, heated shelters for stray dogs. These rooftop refuges will be easily accessible and serve as safe havens during winter. To engage the community and enhance urban aesthetics, these shelters will feature art installations or murals and incorporate green spaces for natural insulation and exploration.',
            image: '../images/P5C.png',
        },
        {id: 'projectB',
            verb:'To Stay Safe',
            projectTitle:'Dog Tour Guide',
            description:'The proposed solution is a unique program where stray dogs are trained to become interactive guides at key Soviet-era buildings in Chisinau. This small, dedicated spaces within these historic sites where people can visit, interact with the dogs along the tour. This approach serves a dual purpose: it provides much-needed companionship for the dogs and offers a unique engaging historical experience for visitors.',
            image: '../images/P5A.png',
        },
        {id: 'projectC',
            verb:'To Feel Wanted',
            projectTitle:'Smart Crossings',
            description:'Implementing smart animal-safe crossings equipped with infrared sensors in key areas of Chisinau directly addresses the city’s unique challenge. These crossings offer real-time detection of stray dogs ensuring adaptive traffic signals and visible alerts for enhanced safety.',
            image: '../images/P5B.png',
        },
] 
    },

    {
        id: 'portfolio6',
        title: 'The Social Water Front',
        description: 'Design for Blend',
        imageURL: 'url(images/P6.png)',
        videoURL: 'videos/P6.mp4',
        symbolURL: 'symbols/P6.svg',
        bigtext: 'Merging into Lausanne with Nordic-Inspired Social Space',
        imageCover: "../images/P6.png",
        textProjectDescription: "In the Design for Blend process, we had to begin with a base image and use the 'describe' tool from Midjourney to position our solution within the image. We drew inspiration for our solution from collages and scene pieces. Our idea was to build a social waterfront building with a Nordic architecture beside Lac Léman in Lausanne. It had a two-tier design, a 'floating' platform, and a view of the mountains from the top. ",
        imageContentRight: "../images/P6.png",
        textProcessLeft: "Combining through a Midjourney's blend + the base image description (generated through AI) and the structural description of the building, we were able to generate a solution within a particular scene",
        imageProcessCards: [
            {image:"../images/P6Images/P6_Setting1.png", text:"initial setting"},
            {image:"../images/P6Images/P6_Setting2.png", text:"found setting"},
            {image:"../images/P6Images/P6_GeneratedSetting.png", text:"generated setting from left"},
            {image:"../images/P6Images/P6_screenshot2.png", text:"template for process generation"},
        ],
        imageCenter: "../images/P6Images/P6_8.png",
        textImproving: "We would like to explore less material heavy solutions as well as different user groups whom would use the social space.  The Midjourney feature (Vary by Region) generates solutions that are more viable, however yield less imaginative and smaller scoped structures.",
        textMyExperienceAndOpinion: "Our project showcased Midjourney's unique and effective industry application, combining it with ChatGPT for a display of AI's capabilities. Initially, progress was gradual as we balanced composition and camera angles while seeking a visually appealing location. Midjourney's suggestions, like incorporating swings, sparked creativity. Our success stemmed from a strong base image inspired by Nordic design and Olafur Eliasson, enhanced by detailed tweaking.",
        imageResultsCards: [
            {image:"../images/P6Images/P6_4.png", text:""},
            {image:"../images/P6Images/P6_5.png", text:""},
            {image:"../images/P6Images/P6_6.png", text:""},
            {image:"../images/P6Images/P6_7.png", text:""},
            {image:"../images/P6Images/P6_8.png", text:""},
            {image:"../images/P6Images/P6_9.png", text:""},
            {image:"../images/P6Images/P6_10.png", text:""},
        ],
    },

];

export default PORTFOLIOPROJECTS;