export const PORTFOLIOPROJECTS = [
    {
        // for title page
        id: 'portfolio1',
        title: 'Transcarry',
        description: 'Design by Empathy.',
        imageURL: 'url(images/P1.png)',
        videoURL: 'videos/P1.mp4',
        symbolURL: 'symbols/P1.svg',
        bigtext: 'Shopping that waits for you where you need it',
        // for project page
        imageCover: "../images/P1.png",
        textProjectDescription: "This project on the theme of Sustainability. We reflected on the issues of car pollution and reducing carbon emissions. With convenience standing out as the main driver behind the widespread use of car. Therefore, convenience often being the motivation for social non-working woman. Therefore, we aimed at creating a sustainable solution that encourages sustainable modes of transport.<br><br>Our idea was around storing groceries whilst in the city and having it automatically transported (like plane luggage) to the destination. Our, 47 year old Alice, might be going to a social event after, in charge of chores around the city - so we wanted it to be convenient for them. ",
        imageContentRight: "../images/P1.png",
        textProcessLeft: "In this Design For Empathy process, we first created personas with a user experience story and a problem statement. We plotted an experience map before exploring solutions on a verb diagram. ",
        imageProcessCards: [
            {image: "../images/P1Extras/personas.png", text:"Personas"},
            {image: "../images/P1Extras/ExperienceMap.png", text:"Experience Map"},
            {image: "../images/P1Extras/transcarryUserJourney.png", text:"User Journey"},
            {image: "../images/P1Extras/verbBoard.png", text:"Verb Board"},
        ],
        imageCenter: "../images/P1A.png",
        textImproving: "To improve our solution, we could explore alternative carrier methods like crates and compare them to traditional delivery trucks. The main advantage of using TransCarry is preserving the in-store shopping experience, which we can incentivize through discounts, cooking workshops, and partnerships with local shops. Additionally, we can enable customers to scan items in-store, automatically sending them to destination lockers for added convenience and a more seamless shopping experience.",
        textMyExperienceAndOpinion: "Creating personas is a traditional but important stage. Coming up with a persona helps to find insightful problems. I like ther focus on a verb and its touchpoints to help find solutions. However, I feel a disconnect between this verb/touchpoint stage and the persona stage, as the emotional needs of the persona does not take priority, instead their actions.",
        imageResultsCards: [
            {image:"../images/P1Extras/SolutionStatement.png", text:"Final Solution Statement"},
            {image:"../images/P1Extras/oldOutput.png", text:"Another generation"},
            {image:"../images/P1Extras/UserJourneySketch.jpeg", text:"Original User Journey Sketch"},
        ],
    },

    {
        id: 'portfolio2',
        title: 'Dog-beds',
        description: 'Design for Environmental and Social Transformations',
        imageURL: 'url(images/P2.png)',
        videoURL: 'videos/P2Square.mp4',
        symbolURL: 'symbols/P2.svg',
        bigtext: 'Upcycling old fabrics to Dog-beds',
        imageCover: "../images/P2.png",
        textProjectDescription: "The life cycle of a product, and the complete experience of touchpoints was empahsized. The focus was on bringing new life to an old product. <br> <br> In our solution, we decided upon upcycling dog beds. For the experience, When customers enter a store, they can select a bed size, and can either donate fabric or pay a supplementary fee to cover the balance. This fee also funds fabric waste purchases from companies, preventing waste. All donated fabrics are categorized, quality- checked, and sanitized. With donors able trace their contributed clothing, watching its transformation into a bed throughout the week. Upon bed completion, customers are notified for pickup and can snap a memorable photo with their dog and the new bed at the in-store booth. ",
        imageContentRight: "../images/P2Extras/DonationStore.png",
        textProcessLeft: "We focused on the most important attributes to our topic to use as keywords in our generatoin. Using weightings (according to our refinement matric), we highlighted the keywords to change the focus and direction of AI Generation. Interestingly, MidJourney inspired me to make dog beds out of old fabrics after generating our initial idea of blankets placed a dog within blankets instead of a person when manipulating weightings of certain words within the prompt. <br> There are several active touch points: the collection of old fabrics, processing and the new product.<br> We wanted to encourage donation, and thought about the personalisation of using one’s own fabrics. Specifically, the scent of a dog’s owner fabric can be comforting to the dog. This became the unique selling point of our proposition.",
        imageProcessCards: [
            {image:"../images/P2Extras/1GenerativeMatric.png", text:"Generative Matrix with our first item of Amenities Kits"},
            {image:"../images/P2Extras/Refinement Matric.png", text:"Refining Prompts"},
            {image:"../images/P2Extras/Interaction Diagram.png", text:"Interaction Diagram"},
            {image:"../images/P2Extras/MidjourneyScreenshot.png", text:"Midjourney Screenshot - turning people into dogs"},
        ],
        imageCenter: "../images/P2Extras/PhotoboothDog.png",
        textImproving: "In order to improve our solution, we could partner with charity shops for clothes that haven’t sold, allowing users to easily access high-quality fabrics for their dog beds and may develop for other pets.",
        textMyExperienceAndOpinion: "This was particularly exciting using architectural processes in experience design. This tweaking of certain attributes makes you really consider what is important for your user. It provides a way to explore. For us, we used the morphological box process to open the scope, as we found our new problem and solution through Midjourney.",
        imageResultsCards: [
            {image:"../images/P2Extras/PhotoboothDog.png", text:"Photobooth Dog"},
            {image:"../images/P2Extras/celerei_photo_booth._A_girl_fa8be3d2-c3a2-4fb9-b920-cb85e1ea4c8e.png", text:"Example of Generation attempts"},
            {image:"../images/P2Extras/celerei_photo_shoot_setup_with_light_orange_background._A_girl__50670507-4fdb-4fba-8b0b-843098664748.png", text:"Turning into an experience"},
            {image:"../images/P2Extras/myPhotoshop.png", text:"My Photoshop image to try getting the right elements"},
            {image:"../images/P2Extras/weightingClothes.png", text:"Output looks Photoshopped too!"},
        ],
    },

    {
        id: 'portfolio3',
        title: 'Architech',
        description: 'Design Instruments for Architects',
        imageURL: 'url(images/P3.png)',
        videoURL: 'videos/P3.mp4',
        symbolURL: 'symbols/P3.svg',
        bigtext: 'Elevating Design with flawless plans from concepts - visible and automatically correct',
        imageCover: "../images/P3.png",
        textProjectDescription: "This project was to focus on the needs of Architects. Our initial user group pain was the manual task of transferring paper plans into digital. We took it further through this method of inspiration and our solution was an app that will translate the paper concept sketches into 3D digital models by making a quick rendering. The app would, provide feedback and auto-correct on your paper plans, including revising dimensions using design rules and provide advice along guidelines.",
        imageContentRight: "../images/P3.png",
        textProcessLeft: "Our process involved taking inspiration and applying it for an architectural problem. We used a quadrant to realise our solution. Taking a problem and solution from another domain and applying it to our architectural problrm. Our inspiration came from scanning physical cards to create a virtual card on your mobile.",
        imageProcessCards: [
            {image:"../images/P3Extras/image (6).png", text:"Inspiration Template"},
            {image:"../images/P3Extras/image (7).png", text:"Experience Journey"},
            {image:"../images/P3Extras/image (8).png", text:"Project Description"},
            {image:"../images/P3Extras/image (9).png", text:"Relevance and Impact"},
        ],
        imageCenter: "../images/P3Extras/Card.png",
        textImproving: "In terms of improvement, we could present the 3D model in Augment Reality form or an instant 3D print of the model is created. The app will translate the paper concept sketches into 3D digital models by making a quick rendering. The app would, provide feedback and auto-correct on your paper plans, including revising dimensions using design rules and provide advice along guidelines.Another idea was scanning multiple paper concept sketches, finding patterns in style from user data for the app to create predictive design recommendations.",
        textMyExperienceAndOpinion: "This was a relatively effective method for finding a solution. However, there were risks in that we had an architectural problem and idea, and we reversed the process to find a solution in another domain. I had recently come across a similar method in my Design Research for Innovation module - as a method named State of the Art, which took inspiration from other domains especially contemporary art.",
        imageResultsCards: [
            {image:"../images/P3Extras/image (4).png", text:"Problem 1"},
            {image:"../images/P3Extras/image (5).png", text:"Problem 2"},
            {image:"../images/P3Extras/model.png", text:"Generations - modelling to screen"},
            {image:"../images/P3Extras/rendering.png", text:"Generations - rendering to screen"},
        ],
    },

    {
        id: 'portfolio4',
        title: 'Dunlop Golf Glove',
        description: 'Design With Style',
        imageURL: 'url(images/P4.png)',
        videoURL: 'videos/P4.mp4',
        symbolURL: 'symbols/P4.svg',
        bigtext: 'A stylish recovery inspired',
        imageCover: "../images/P4.png",
        textProjectDescription: "Description for Project 4 left",
        imageContentRight: "Image for Project 4 right",
        textProcessLeft: "Process left text for Project 4",
        imageProcessCards: [
            {image:"https://source.unsplash.com/random?5", text:""},
            {image:"https://source.unsplash.com/random?2", text:""},
            {image:"https://source.unsplash.com/random?3", text:""},
            {image:"https://source.unsplash.com/random?4", text:""},
        ],
        imageCenter: "https://source.unsplash.com/random",
        textImproving: "...",
        textMyExperienceAndOpinion: "Blah blah blah",
        imageResultsCards: [
            {image:"https://source.unsplash.com/random?6", text:""},
            {image:"https://source.unsplash.com/random?7", text:""},
            {image:"https://source.unsplash.com/random?8", text:""},
            {image:"https://source.unsplash.com/random?9", text:""},
        ],
    },

    {
        id: 'portfolio5',
        title: 'Winter in Chisnau',
        description: 'Design for Context',
        imageURL: 'url(images/P5A.png)',
        videoURL: 'videos/P5BSquare.mp4',
        symbolURL: 'symbols/P5.svg',
        bigtext: 'Improving the city, improving dog welfare',
        imageCover: "../images/P5.png",
        textProjectDescription: "Description for Project 5 left",
        imageContentRight: "Image for Project 5 right",
        textProcessLeft: "Process left text for Project 5",
        imageProcessCards: [
            {image:"https://source.unsplash.com/random?5", text:""},
            {image:"https://source.unsplash.com/random?2", text:""},
            {image:"https://source.unsplash.com/random?3", text:""},
            {image:"https://source.unsplash.com/random?4", text:""},
        ],
        imageCenter: "https://source.unsplash.com/random",
        textImproving: "...",
        textMyExperienceAndOpinion: "Blah blah blah",
        imageResultsCards: [
            {image:"https://source.unsplash.com/random?6", text:""},
            {image:"https://source.unsplash.com/random?7", text:""},
            {image:"https://source.unsplash.com/random?8", text:""},
            {image:"https://source.unsplash.com/random?9", text:""},
        ],
    },

    {
        id: 'portfolio6',
        title: 'The Social Water Front',
        description: 'Design for Blend',
        imageURL: 'url(images/P6.png)',
        videoURL: 'videos/P6.mp4',
        symbolURL: 'symbols/P6.svg',
        bigtext: 'Merging into Lausanne with Nordic-Inspired Social Space',
        imageCover: "../images/P1.png",
        textProjectDescription: "Description for Project 6 left",
        imageContentRight: "Image for Project 6 right",
        textProcessLeft: "Process left text for Project 6",
        imageProcessCards: [
            {image:"https://source.unsplash.com/random?5", text:""},
            {image:"https://source.unsplash.com/random?2", text:""},
            {image:"https://source.unsplash.com/random?3", text:""},
            {image:"https://source.unsplash.com/random?4", text:""},
        ],
        imageCenter: "https://source.unsplash.com/random",
        textImproving: "...",
        textMyExperienceAndOpinion: "Blah blah blah",
        imageResultsCards: [
            {image:"https://source.unsplash.com/random?6", text:""},
            {image:"https://source.unsplash.com/random?7", text:""},
            {image:"https://source.unsplash.com/random?8", text:""},
            {image:"https://source.unsplash.com/random?9", text:""},
        ],
    },

];

export default PORTFOLIOPROJECTS;