export const PORTFOLIOPROJECTS = [
    {
        // for title page
        id: 'portfolio1',
        title: 'Transcarry',
        description: 'Design by Empathy.',
        imageURL: 'url(images/P1.png)',
        videoURL: 'videos/P1.mp4',
        symbolURL: 'symbols/P1.svg',
        bigtext: 'Shopping that waits for you where you need it',
        // for project page
        imageCover: "../images/P1.png",
        textProjectDescription: "Description for Project 1",
        imageContentRight: "../images/P1.png",
        textProcessLeft: "Daring to be different and drawing inspiration from the sleek black and green Axopar that cruises above Cayman",
        textProcessRight: "dgdrgdrg",
        imageProcessCards: [
            {image: "../images/P1.png", text:"A great image"},
            {image: "../images/P2.png", text:"Very cool"},
            {image: "../images/P3.png", text:"What an interesting process!"},
            {image: "../images/P4.png", text:"Hey!"},
        ],
        imageCenter: "https://source.unsplash.com/random",
        textMyExperienceAndOpinion: "Blah blah blah",
        imageResultsCards: [
            {image:"https://source.unsplash.com/random?6", text:""},
            {image:"https://source.unsplash.com/random?7", text:""},
            {image:"https://source.unsplash.com/random?8", text:""},
        ],
    },

    {
        id: 'portfolio2',
        title: 'Dog-beds',
        description: 'Design for Comfort',
        imageURL: 'url(images/P2.png)',
        videoURL: 'videos/P2.mp4',
        symbolURL: 'symbols/P2.svg',
        bigtext: 'Project Big Text 2',
        imageCover: "https://source.unsplash.com/random?2",
        textProjectDescription: "Description for Project 2 left",
        imageContentRight: "Image for Project 2 right",
        textProcessLeft: "Process left text for Project 2",
        textProcessRight: "Process right text for Project 2",
        imageProcessCards: [
            {image:"https://source.unsplash.com/random?5", text:""},
            {image:"https://source.unsplash.com/random?2", text:""},
            {image:"https://source.unsplash.com/random?3", text:""},
            {image:"https://source.unsplash.com/random?4", text:""},
        ],
        imageCenter: "https://source.unsplash.com/random/?banana",
        textMyExperienceAndOpinion: "Blah blah blah",
        imageResultsCards: [
            {image:"https://source.unsplash.com/random?6", text:""},
            {image:"https://source.unsplash.com/random?7", text:""},
            {image:"https://source.unsplash.com/random?8", text:""},
            {image:"https://source.unsplash.com/random?9", text:""},
        ],
    },

    {
        id: 'portfolio3',
        title: 'Architech',
        description: 'Design Instruments for Architects',
        imageURL: 'url(images/P3.png)',
        videoURL: 'videos/P3.mp4',
        symbolURL: 'symbols/P3.svg',
        bigtext: 'Elevating Design with flawless plans from concepts - visible and automatically correct',
        imageCover: "https://source.unsplash.com/random?3",
        textProjectDescription: "Description for Project 3 left",
        imageContentRight: "Image for Project 3 right",
        textProcessLeft: "Process left text for Project 3",
        textProcessRight: "Process right text for Project 3",
        imageProcessCards: [
            {image:"https://source.unsplash.com/random?5", text:""},
            {image:"https://source.unsplash.com/random?2", text:""},
            {image:"https://source.unsplash.com/random?3", text:""},
            {image:"https://source.unsplash.com/random?4", text:""},
        ],
        imageCenter: "https://source.unsplash.com/random/?blueberry",
        textMyExperienceAndOpinion: "Blah blah blah",
        imageResultsCards: [
            {image:"https://source.unsplash.com/random?6", text:""},
            {image:"https://source.unsplash.com/random?7", text:""},
            {image:"https://source.unsplash.com/random?8", text:""},
            {image:"https://source.unsplash.com/random?9", text:""},
        ],
    },

    {
        id: 'portfolio4',
        title: 'Dunlop Golf Glove',
        description: 'Design With Style',
        imageURL: 'url(images/P4.png)',
        videoURL: 'videos/P4.mp4',
        symbolURL: 'symbols/P4.svg',
        bigtext: 'A stylish recovery inspired',
        imageCover: "https://source.unsplash.com/random?4",
        textProjectDescription: "Description for Project 4 left",
        imageContentRight: "Image for Project 4 right",
        textProcessLeft: "Process left text for Project 4",
        textProcessRight: "Process right text for Project 4",
        imageProcessCards: [
            {image:"https://source.unsplash.com/random?5", text:""},
            {image:"https://source.unsplash.com/random?2", text:""},
            {image:"https://source.unsplash.com/random?3", text:""},
            {image:"https://source.unsplash.com/random?4", text:""},
        ],
        imageCenter: "https://source.unsplash.com/random",
        textMyExperienceAndOpinion: "Blah blah blah",
        imageResultsCards: [
            {image:"https://source.unsplash.com/random?6", text:""},
            {image:"https://source.unsplash.com/random?7", text:""},
            {image:"https://source.unsplash.com/random?8", text:""},
            {image:"https://source.unsplash.com/random?9", text:""},
        ],
    },

    {
        id: 'portfolio5',
        title: 'Winter in Chisnau',
        description: 'Design for Context',
        imageURL: 'url(images/P5A.png)',
        videoURL: 'videos/P5BSquare.mp4',
        symbolURL: 'symbols/P5.svg',
        bigtext: 'Improving the city, improving dog welfare',
        imageCover: "https://source.unsplash.com/random?5",
        textProjectDescription: "Description for Project 5 left",
        imageContentRight: "Image for Project 5 right",
        textProcessLeft: "Process left text for Project 5",
        textProcessRight: "Process right text for Project 5",
        imageProcessCards: [
            {image:"https://source.unsplash.com/random?5", text:""},
            {image:"https://source.unsplash.com/random?2", text:""},
            {image:"https://source.unsplash.com/random?3", text:""},
            {image:"https://source.unsplash.com/random?4", text:""},
        ],
        imageCenter: "https://source.unsplash.com/random",
        textMyExperienceAndOpinion: "Blah blah blah",
        imageResultsCards: [
            {image:"https://source.unsplash.com/random?6", text:""},
            {image:"https://source.unsplash.com/random?7", text:""},
            {image:"https://source.unsplash.com/random?8", text:""},
            {image:"https://source.unsplash.com/random?9", text:""},
        ],
    },

    {
        id: 'portfolio6',
        title: 'The Social Water Front',
        description: 'Design for Blend',
        imageURL: 'url(images/P6.png)',
        videoURL: 'videos/P6.mp4',
        symbolURL: 'symbols/P6.svg',
        bigtext: 'Merging into Lausanne with Nordic-Inspired Social Space',
        imageCover: "https://source.unsplash.com/random?6",
        textProjectDescription: "Description for Project 6 left",
        imageContentRight: "Image for Project 6 right",
        textProcessLeft: "Process left text for Project 6",
        textProcessRight: "Process right text for Project 6",
        imageProcessCards: [
            {image:"https://source.unsplash.com/random?5", text:""},
            {image:"https://source.unsplash.com/random?2", text:""},
            {image:"https://source.unsplash.com/random?3", text:""},
            {image:"https://source.unsplash.com/random?4", text:""},
        ],
        imageCenter: "https://source.unsplash.com/random",
        textMyExperienceAndOpinion: "Blah blah blah",
        imageResultsCards: [
            {image:"https://source.unsplash.com/random?6", text:""},
            {image:"https://source.unsplash.com/random?7", text:""},
            {image:"https://source.unsplash.com/random?8", text:""},
            {image:"https://source.unsplash.com/random?9", text:""},
        ],
    },

];

export default PORTFOLIOPROJECTS;