export const portfolioProjects = [
    {
        // for title page
        id: 'portfolio1',
        title: 'Transcarry',
        description: 'Design by Empathy.',
        imageURL: 'url(images/P1.png)',
        videoURL: 'videos/P1.mp4',
        symbolURL: 'symbols/P1.svg',
        bigtext: 'Shopping that waits for you where you need it',
        // for project page
        backgroundImage: "https://source.unsplash.com/random?6",
        textContentLeft: "Description for Project 1",
        imageContentRight: "Description for Project 1",
        textContentProcessLeft: "Daring to be different and drawing inspiration from the sleek black and green Axopar that cruises above Cayman",
        textContentProcessRight: "dgdrgdrg",
        imageCenter: "https://source.unsplash.com/random",
        textMyExperienceAndOpinion: "Blah blah blah",
        imageCard1: "https://source.unsplash.com/random?5",
        imageCard2: "https://source.unsplash.com/random?2",
        imageCard3: "https://source.unsplash.com/random?3",
        imageCard4: "https://source.unsplash.com/random?4",



    },

    {
        id: 'portfolio2',
        title: 'Dog-beds',
        description: 'Design for Comfort',
        imageURL: 'url(images/P2.png)',
        videoURL: 'videos/P2.mp4',
        symbolURL: 'symbols/P2.svg',
        bigtext: 'Project Big Text 2',
        backgroundImage: "https://source.unsplash.com/random?2",
        textContentLeft: "Description for Project 2 left",
        imageContentRight: "Image for Project 2 right",
        textContentProcessLeft: "Process left text for Project 2",
        textContentProcessRight: "Process right text for Project 2",
        imageCenter: "https://source.unsplash.com/random?center2",
        textMyExperienceAndOpinion: "My experience and opinion on Project 2",
        imageCard1: "https://source.unsplash.com/random?25",
        imageCard2: "https://source.unsplash.com/random?22",
        imageCard3: "https://source.unsplash.com/random?23",
        imageCard4: "https://source.unsplash.com/random?24"
    },

    {
        id: 'portfolio3',
        title: 'Architech',
        description: 'Design Instruments for Architects',
        imageURL: 'url(images/P3.png)',
        videoURL: 'videos/P3.mp4',
        symbolURL: 'symbols/P3.svg',
        bigtext: 'Elevating Design with flawless plans from concepts - visible and automatically correct',
        backgroundImage: "https://source.unsplash.com/random?3",
        textContentLeft: "Description for Project 3 left",
        imageContentRight: "Image for Project 3 right",
        textContentProcessLeft: "Process left text for Project 3",
        textContentProcessRight: "Process right text for Project 3",
        imageCenter: "https://source.unsplash.com/random?center3",
        textMyExperienceAndOpinion: "My experience and opinion on Project 3",
        imageCard1: "https://source.unsplash.com/random?35",
        imageCard2: "https://source.unsplash.com/random?32",
        imageCard3: "https://source.unsplash.com/random?33",
        imageCard4: "https://source.unsplash.com/random?34"
    },

    {
        id: 'portfolio4',
        title: 'Dunlop Golf Glove',
        description: 'Design With Style',
        imageURL: 'url(images/P4.png)',
        videoURL: 'videos/P4.mp4',
        symbolURL: 'symbols/P4.svg',
        bigtext: 'A stylish recovery inspired',
        backgroundImage: "https://source.unsplash.com/random?4",
        textContentLeft: "Description for Project 4 left",
        imageContentRight: "Image for Project 4 right",
        textContentProcessLeft: "Process left text for Project 4",
        textContentProcessRight: "Process right text for Project 4",
        imageCenter: "https://source.unsplash.com/random?center4",
        textMyExperienceAndOpinion: "My experience and opinion on Project 4",
        imageCard1: "https://source.unsplash.com/random?45",
        imageCard2: "https://source.unsplash.com/random?42",
        imageCard3: "https://source.unsplash.com/random?43",
        imageCard4: "https://source.unsplash.com/random?44"
    },

    {
        id: 'portfolio5',
        title: 'Winter in Chisnau',
        description: 'Design for Context',
        imageURL: 'url(images/P5A.png)',
        videoURL: 'videos/P5BSquare.mp4',
        symbolURL: 'symbols/P5.svg',
        bigtext: 'Improving the city, improving dog welfare',
        backgroundImage: "https://source.unsplash.com/random?5",
        textContentLeft: "Description for Project 5 left",
        imageContentRight: "Image for Project 5 right",
        textContentProcessLeft: "Process left text for Project 5",
        textContentProcessRight: "Process right text for Project 5",
        imageCenter: "https://source.unsplash.com/random?center5",
        textMyExperienceAndOpinion: "My experience and opinion on Project 5",
        imageCard1: "https://source.unsplash.com/random?55",
        imageCard2: "https://source.unsplash.com/random?52",
        imageCard3: "https://source.unsplash.com/random?53",
        imageCard4: "https://source.unsplash.com/random?54"
    },

    {
        id: 'portfolio6',
        title: 'The Social Water Front',
        description: 'Design for Blend',
        imageURL: 'url(images/P6.png)',
        videoURL: 'videos/P6.mp4',
        symbolURL: 'symbols/P6.svg',
        bigtext: 'Merging into Lausanne with Nordic-Inspired Social Space',
        backgroundImage: "https://source.unsplash.com/random?6",
        textContentLeft: "Description for Project 6 left",
        imageContentRight: "Image for Project 6 right",
        textContentProcessLeft: "Process left text for Project 6",
        textContentProcessRight: "Process right text for Project 6",
        imageCenter: "https://source.unsplash.com/random?center6",
        textMyExperienceAndOpinion: "My experience and opinion on Project 6",
        imageCard1: "https://source.unsplash.com/random?65",
        imageCard2: "https://source.unsplash.com/random?62",
        imageCard3: "https://source.unsplash.com/random?63",
        imageCard4: "https://source.unsplash.com/random?64"
    },

];

export default portfolioProjects;